[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"  # Path to your functions directory

[dev]
  functions = "functions"  # Ensure this points to your functions directory

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/scrape"
  to = "/.netlify/functions/server" # Adjust the endpoint as needed
  status = 200
  force = true