[build]
  command = "npm run build"
  publish = "build"
  
[functions]
  directory = "functions"

[[redirects]]
  from = "/api/scrape"
  to = "/.netlify/functions/server" # Adjust the endpoint as needed
  status = 200
  force = true